version: '3.7'

services:
  backend:
    build:
      context: .
      args:
        GIT_HASH: docker-compose
    ports:
    - 8080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_CONNECTION: sqlite:///data/sqlite.db?mode=rwc
      VECTOR_CONNECTION: opensearch+https://admin:admin@docdb:9200
    depends_on:
      - docdb
    volumes:
      - ./data:./data
  docdb:
    image: opensearchproject/opensearch:2
    environment:
      - discovery.type=single-node
    volumes:
      - ./data/opensearch:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer

